on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: release_please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release_please.outputs.release_created }}

      - name: Install pnpm 
        if: ${{ steps.release_please.outputs.release_created }}
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        if: ${{ steps.release_please.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        if: ${{ steps.release_please.outputs.release_created }}
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ steps.release_please.outputs.release_created }}
        run: pnpm run build

      - name: Prepare Publish
        if: ${{ steps.release_please.outputs.release_created }}
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> .npmrc

      - name: Publish
        if: ${{ steps.release_please.outputs.release_created }}
        run: pnpm publish --no-git-checks
